---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 瞭解工作負載工廠的 AI 工作負載功能有哪些新功能。 
---
= 新功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
瞭解工作負載工廠的通用 AI 工作負載功能有哪些新功能。



== 2024 年 11 月 3 日



=== 使用資料欄遮罩個人識別資訊

泛用型 AI 工作負載採用 BlueXP  分類技術、引進資料 guardrails 功能。資料安全欄功能可識別及遮罩個人識別資訊（ PII ）、協助您維持法規遵循、並強化敏感組織資料的安全性。

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#create-and-configure-the-knowledge-base["建立知識庫"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["瞭解 BlueXP 分類"^]



== 2024 年 9 月 29 日



=== 快照與還原支援知識庫磁碟區

您現在可以取得知識庫的時間點複本、以保護您的泛用 AI 工作負載資料。這可讓您保護資料、避免意外遺失或測試知識庫設定的變更。您可以隨時還原舊版的知識庫磁碟區。

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["拍攝知識庫磁碟區的快照"]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["還原知識庫磁碟區的快照"]



=== 暫停排程掃描

您現在可以暫停排程的資料來源掃描。根據預設、泛化 AI 工作負載會每天掃描每個資料來源、以便將新資料擷取到每個知識庫中。如果您不想擷取最新的變更（例如在測試期間或還原快照時）、您可以暫停排程的掃描、並隨時繼續進行。

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html["管理知識庫"]



=== 知識庫現在支援資料保護磁碟區

選取知識庫磁碟區時、您現在可以選擇屬於 NetApp SnapMirror 複寫關係一部分的資料保護磁碟區。這可讓您將知識庫儲存在已受 SnapMirror 複寫保護的磁碟區上。

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html["識別要整合到知識庫中的資料來源"]



== 2024 年 9 月 1 日



=== 其他的分塊策略

泛用 AI 工作負載現在支援資料來源的多重句子區塊和重疊區塊。



=== 每個知識庫的專用磁碟區

現在、泛用 AI 工作負載會為每個新知識庫建立專屬的 Amazon FSX for NetApp ONTAP Volume 、為每個知識庫啟用個別的快照原則、並針對故障和資料中毒提供更好的保護。



== 2024 年 8 月 4 日



=== Amazon CloudWatch 記錄整合

現在、泛用 AI 工作負載已與 Amazon CloudWatch 記錄整合、可讓您監控泛用 AI 工作負載記錄檔。



=== 例如： chatbot 應用程式

NetApp 工作負載工廠 GenAI 範例應用程式可讓您在網路型的聊天應用程式中直接與 IT 互動，從已發佈的 NetApp 工作負載工廠知識庫測試驗證和擷取。



== 2024 年 7 月 7 日



=== GenAI 工作負載工廠的初始版本

初始版本包含開發知識庫的功能、可藉由內嵌組織資料來自訂。使用者可透過聊天機器人應用程式存取知識庫。這項功能可確保針對組織特定問題做出準確且相關的回應、提高所有使用者的滿意度與生產力。
