---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 瞭解工作負載工廠的 AI 工作負載功能有哪些新功能。 
---
= GenAI BlueXP  工作負載工廠的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
瞭解工作負載工廠的通用 AI 工作負載功能有哪些新功能。



== 2025 年 04 月 5 日



=== 支援 NetApp ONTAP Connector for Amazon Q

此版本的 GenAI 引進 NetApp ONTAP Connector for Amazon Q 的支援，可讓您為 Amazon Q Business 建立連接器。與為 Amazon Bedrock 建立 GenAI 知識庫相比，較少的初始組態，可快速輕鬆地利用 Amazon Q Business AI 助理。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["為 Amazon Q Business 建立 GenAI Connector"]



=== 增強的聊天模式支援

GenAI 現在支援下列額外的聊天模式以供知識庫使用：

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AI 機型"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titan 文字模型"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["中繼 Llama 機型"^]
* link:https://docs.ai21.com/["Jamba 1.5 機型"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohere Command 模型"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Deepseek 機型"^]


GenAI 支援 Amazon Bedrock 支援的每個供應商機型：link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon 基礎架構支援的基礎模型"^]

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html["建立 GenAI 知識庫"]



=== 更新的權限術語

工作負載原廠使用者介面與文件現在使用「唯讀」來指稱讀取權限，而「讀取寫入」則指自動化權限。



== 2025 年 3 月 02 日



=== 嵌入式聊天機器人程式增強功能

您現在可以直接將問題和回應複製到剪貼簿，調整聊天視窗的大小，以及變更其標題。此外，聊天回應現在可以包含表格，這些表格也可以複製。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["測試 GenAI 知識庫"]



=== 聊天回應引文支援

聊天回應現在包含的引文會列出用來產生回應的檔案和資料區塊。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["測試 GenAI 知識庫"]



=== 增強的檔案類型支援

此版本的 GenAI 提供增強的檔案支援：

* 聊天模式提供更好的 CSV 支援。這可在從 CSV 檔案查詢資料時，提供更有用的回應。
* GenAI 現在可以從資料來源擷取 Apache Parquet 檔案。
* GenAI 現在支援擷取包含影像的 Microsoft Word DOCX 檔案。系統會掃描 DOCX 文件中內嵌的影像，並在回應知識庫查詢時，納入內嵌影像的文字洞見。


link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["支援的資料來源檔案格式"]



== 2025 年 02 月 2 日



=== 支援 Amazon Nova 基礎模式

GenAI 現在支援 Amazon Nova 基礎模式。支援 Amazon Nova Micro ， Amazon Nova Lite 和 Amazon Nova Pro 。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/requirements-knowledge-base.html["GenAI 需求"]



=== 資料來源的檔案類型篩選

GenAI 現在支援在新增資料來源時，選取要納入資料來源掃描的特定檔案類型。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["將資料來源新增至知識庫"]



=== 資料來源的檔案修改日期篩選

GenAI 現在支援篩選檔案，可在新增資料來源時，依修改日期納入資料來源掃描。您可以為包含的檔案選擇修改日期範圍。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["將資料來源新增至知識庫"]



=== 支援影像檔案，並加強支援 PDF 檔案

GenAI 現在支援強化對知識庫查詢的回應，從影像和圖表說明以及文件文字中獲得深入見解，進而提供更豐富，更高品質的答案。GenAI 現在可以掃描 PDF 檔案中的影像檔案和影像（也稱為多模式檔案支援）。如果您選擇掃描影像或 PDF 檔案，則會將影像中的文字（包括內嵌於 PDF 文件中的影像）掃描至資料來源，而掃描結果中的洞見則會包含在知識庫查詢的回應中。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["將資料來源新增至知識庫"]



=== 混合式搜尋與重新部署支援

GenAI 現在可以使用混合式搜尋並重新排列結果的順序，大幅提升搜尋結果的相關性和準確度。混合式搜尋結合了傳統關鍵字型搜尋的優勢，以及進階密集向量型語義搜尋技術。標準關鍵字搜尋結果會以接近的相符項目和語言差異加以擴充，以增強相關性。然後 GenAI 使用進階重新排名模型（例如 Cohere Rerank 和 Amazon Rerank ）進一步精簡這些結果，並傳回最相關的結果。這項功能適用於新建立的知識庫。

link:https://docs.netapp.com/us-en/workload-genai/general/ai-workloads-overview.html#benefits-of-using-genai-to-create-generative-ai-applications["瞭解 GenAI 的 BlueXP  工作負載工廠"]



== 2025 年 1 月 05 日



=== 自訂快照名稱

您現在可以為臨機操作快照提供快照名稱。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["利用快照保護知識庫"]



=== 自訂 AI 引擎執行個體名稱

您現在可以在部署期間為 AI 引擎執行個體提供自訂名稱。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/deploy-infrastructure.html["部署 GenAI 基礎架構"]



=== 重建毀損或遺失的 GenAI 基礎架構

如果您的 AI 引擎執行個體毀損或遭到刪除，您可以讓工作負載在出廠時重新建置。工作負載原廠會在重建完成後，自動將您的知識庫重新附加到基礎架構，以便準備好使用。

link:https://docs.netapp.com/us-en/workload-genai/general/troubleshooting.html["疑難排解"]



== 2024 年 12 月 01 日



=== 從快照複製知識庫

GenAI 的 BlueXP  工作負載工廠現在支援從快照複製知識庫。這可快速恢復知識庫，並利用現有資料來源建立新的知識庫，有助於資料恢復與開發。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#clone-a-knowledge-base["複製知識庫"]



=== 內部部署 ONTAP 叢集探索與複寫

探索內部部署的 ONTAP 叢集資料，並將其複寫至適用於 ONTAP 檔案系統的 FSX ，以便用於豐富 AI 知識庫。所有內部部署探索和複寫工作流程都可以從儲存設備詳細目錄中的全新 * 內部部署 ONTAP （ * ）標籤中進行。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["探索內部部署 ONTAP 的叢集"]



== 2024 年 11 月 3 日



=== 使用資料欄遮罩個人識別資訊

泛用型 AI 工作負載採用 BlueXP  分類技術、引進資料 guardrails 功能。資料安全欄功能可識別及遮罩個人識別資訊（ PII ）、協助您維持法規遵循、並強化敏感組織資料的安全性。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["建立 GenAI 知識庫"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["瞭解 BlueXP 分類"^]



== 2024 年 9 月 29 日



=== 快照與還原支援知識庫磁碟區

您現在可以取得知識庫的時間點複本、以保護您的泛用 AI 工作負載資料。這可讓您保護資料、避免意外遺失或測試知識庫設定的變更。您可以隨時還原舊版的知識庫磁碟區。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["拍攝知識庫磁碟區的快照"]

https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["還原知識庫磁碟區的快照"]



=== 暫停排程掃描

您現在可以暫停排程的資料來源掃描。根據預設、泛化 AI 工作負載會每天掃描每個資料來源、以便將新資料擷取到每個知識庫中。如果您不想擷取最新的變更（例如在測試期間或還原快照時）、您可以暫停排程的掃描、並隨時繼續進行。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html["管理知識庫"]



=== 知識庫現在支援資料保護磁碟區

選取知識庫磁碟區時、您現在可以選擇屬於 NetApp SnapMirror 複寫關係一部分的資料保護磁碟區。這可讓您將知識庫儲存在已受 SnapMirror 複寫保護的磁碟區上。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html["識別要整合到知識庫中的資料來源"]



== 2024 年 9 月 1 日



=== 其他的分塊策略

泛用 AI 工作負載現在支援資料來源的多重句子區塊和重疊區塊。



=== 每個知識庫的專用磁碟區

現在、泛用 AI 工作負載會為每個新知識庫建立專屬的 Amazon FSX for NetApp ONTAP Volume 、為每個知識庫啟用個別的快照原則、並針對故障和資料中毒提供更好的保護。



== 2024 年 8 月 4 日



=== Amazon CloudWatch 記錄整合

現在、泛用 AI 工作負載已與 Amazon CloudWatch 記錄整合、可讓您監控泛用 AI 工作負載記錄檔。



=== 例如： chatbot 應用程式

NetApp 工作負載工廠 GenAI 範例應用程式可讓您在網路型的聊天應用程式中直接與 IT 互動，從已發佈的 NetApp 工作負載工廠知識庫測試驗證和擷取。



== 2024 年 7 月 7 日



=== GenAI 工作負載工廠的初始版本

初始版本包含開發知識庫的功能、可藉由內嵌組織資料來自訂。使用者可透過聊天機器人應用程式存取知識庫。這項功能可確保針對組織特定問題做出準確且相關的回應、提高所有使用者的滿意度與生產力。
