= 
:allow-uri-read: 


[role="tabbed-block"]
====
.新增 FSx for ONTAP 檔案系統
--
. * 選取檔案系統 * ：選取資料來源檔案所在的 ONTAP 檔案系統的 FSX ，然後選取 * 下一步 * 。
. * 選取磁碟區 * ：選取資料來源檔案所在的磁碟區、然後選取 * 下一步 * 。
+
選取使用 SMB 傳輸協定儲存的檔案時、您需要輸入 Active Directory 資訊、其中包括網域、 IP 位址、使用者名稱和密碼。

. * 選取資料來源 * ：根據您儲存檔案的位置選取資料來源位置。這可以是整個磁碟區、或只是磁碟區中的特定資料夾或子資料夾、然後選取 * 下一步 * 。
. * 組態 * ：設定資料來源如何從檔案中擷取資訊，以及其包含在掃描中的檔案：
+
** * 定義資料來源 * ：在 * 區塊策略 * 區段中，定義當資料來源與知識庫整合時， GenAI 引擎如何將資料來源內容分割成區塊。您可以選擇下列其中一個策略：
+
*** * 多重句子區塊 * ：將資料來源中的資訊組織成句子定義的區塊。您可以選擇每個區塊中包含多少句話（最多 100 句）。
*** * 重疊區塊 * ：將資料來源中的資訊組織成字元定義區塊、以重疊鄰近區塊。您可以選擇每個區塊的字元大小、以及每個區塊與相鄰區塊重疊的量。您可以設定 50 到 3000 個字元之間的區塊大小、以及介於 1 到 99% 之間的重疊百分比。
+

NOTE: 選擇高重疊百分比可大幅增加儲存需求、只需稍微改善擷取準確度。



** * 檔案篩選 * ：設定掃描中包含哪些檔案：
+
*** 在「 * 檔案類型支援 * 」區段中，選擇要包含所有類型的檔案，或選擇要包含在資料來源掃描中的個別檔案類型。
+
如果您包含影像或 PDF 檔案，則 GenAI 的 BlueXP  工作負載工廠會剖析影像中的文字（包括 PDF 文件中的影像），這會產生較高的成本。

+
當包含影像的文字資料時，當掃描的文字資料從您的環境傳送至 AWS 時， GenAI 無法從影像中遮罩個人識別資訊（ PII ）。然而，一旦儲存資料， GenAI 資料庫就會隱藏所有 PII 。

+

NOTE: 您選擇在掃描中包含影像檔案，與知識庫聊天模式有關。如果您在掃描中包含影像檔案，則聊天模式必須支援影像。如果在此選取映像檔案類型，您就無法將知識庫切換至不支援映像檔案的聊天模式。

*** 在 * 檔案修改時間篩選器 * 區段中，選擇根據檔案的修改時間來啟用或停用檔案的包含。如果啟用修改時間篩選，請從清單中選取日期範圍。
+

NOTE: 如果您根據修改日期範圍來包含檔案，只要日期範圍不滿足（檔案尚未在您指定的日期範圍內修改），檔案就會排除在定期掃描之外，而且資料來源也不會包含這些檔案。





. 在 * 權限感知 * 區段中，只有當您選取的資料來源位於使用 SMB 通訊協定的磁碟區上時，才能使用此區段，您可以啟用或停用權限感知回應：
+
** * 已啟用 * ：存取此知識庫的聊天機器人程式使用者只能從其存取的資料來源取得查詢回應。
** * 停用 * ：聊天機器人程式的使用者將會使用所有整合式資料來源的內容接收回應。


. 選取 * 新增 * 將此資料來源新增至您的知識庫。


--
.新增通用 NFS 檔案系統
--
. *選擇檔案系統*：輸入資料來源檔案所在的檔案系統主機的 IP 位址或 FQDN，選擇網路共用的 NFS 協議，然後選擇*下一步*。
. * 選取資料來源 * ：根據您儲存檔案的位置選取資料來源位置。這可以是整個磁碟區、或只是磁碟區中的特定資料夾或子資料夾、然後選取 * 下一步 * 。
+

NOTE: 在某些情況下，您可能需要手動輸入 NFS 匯出名稱，然後選擇「擷取目錄」以顯示可用目錄。您可以選擇整個匯出，或僅選擇匯出中的特定資料夾。

. * 組態 * ：設定資料來源如何從檔案中擷取資訊，以及其包含在掃描中的檔案：
+
** * 定義資料來源 * ：在 * 區塊策略 * 區段中，定義當資料來源與知識庫整合時， GenAI 引擎如何將資料來源內容分割成區塊。您可以選擇下列其中一個策略：
+
*** * 多重句子區塊 * ：將資料來源中的資訊組織成句子定義的區塊。您可以選擇每個區塊中包含多少句話（最多 100 句）。
*** * 重疊區塊 * ：將資料來源中的資訊組織成字元定義區塊、以重疊鄰近區塊。您可以選擇每個區塊的字元大小、以及每個區塊與相鄰區塊重疊的量。您可以設定 50 到 3000 個字元之間的區塊大小、以及介於 1 到 99% 之間的重疊百分比。
+

NOTE: 選擇高重疊百分比可大幅增加儲存需求、只需稍微改善擷取準確度。



** * 檔案篩選 * ：設定掃描中包含哪些檔案：
+
*** 在「 * 檔案類型支援 * 」區段中，選擇要包含所有類型的檔案，或選擇要包含在資料來源掃描中的個別檔案類型。
+
如果您包含影像或 PDF 檔案，則 GenAI 的 BlueXP  工作負載工廠會剖析影像中的文字（包括 PDF 文件中的影像），這會產生較高的成本。

+
當包含影像的文字資料時，當掃描的文字資料從您的環境傳送至 AWS 時， GenAI 無法從影像中遮罩個人識別資訊（ PII ）。然而，一旦儲存資料， GenAI 資料庫就會隱藏所有 PII 。

+

NOTE: 您選擇在掃描中包含影像檔案，與知識庫聊天模式有關。如果您在掃描中包含影像檔案，則聊天模式必須支援影像。如果在此選取映像檔案類型，您就無法將知識庫切換至不支援映像檔案的聊天模式。

*** 在 * 檔案修改時間篩選器 * 區段中，選擇根據檔案的修改時間來啟用或停用檔案的包含。如果啟用修改時間篩選，請從清單中選取日期範圍。
+

NOTE: 如果您根據修改日期範圍來包含檔案，只要日期範圍不滿足（檔案尚未在您指定的日期範圍內修改），檔案就會排除在定期掃描之外，而且資料來源也不會包含這些檔案。





. 選擇*新增資料來源*將此資料來源新增至您的知識庫。


--
.新增通用 SMB 檔案系統
--
. *選擇檔案系統*：
+
.. 輸入資料來源檔案所在的檔案系統主機的 IP 位址或 FQDN。
.. 為網路共享選擇 SMB 協定。
.. 輸入 Active Directory 訊息，包括網域、IP 位址、使用者名稱和密碼。
.. 選擇*下一步*。


. * 選取資料來源 * ：根據您儲存檔案的位置選取資料來源位置。這可以是整個磁碟區、或只是磁碟區中的特定資料夾或子資料夾、然後選取 * 下一步 * 。
+

NOTE: 在某些情況下，您可能需要手動輸入 SMB 共享名稱，然後選擇「檢索目錄」以顯示可用目錄。您可以選擇整個共享，或僅選擇共享中的特定資料夾。

. * 組態 * ：設定資料來源如何從檔案中擷取資訊，以及其包含在掃描中的檔案：
+
** * 定義資料來源 * ：在 * 區塊策略 * 區段中，定義當資料來源與知識庫整合時， GenAI 引擎如何將資料來源內容分割成區塊。您可以選擇下列其中一個策略：
+
*** * 多重句子區塊 * ：將資料來源中的資訊組織成句子定義的區塊。您可以選擇每個區塊中包含多少句話（最多 100 句）。
*** * 重疊區塊 * ：將資料來源中的資訊組織成字元定義區塊、以重疊鄰近區塊。您可以選擇每個區塊的字元大小、以及每個區塊與相鄰區塊重疊的量。您可以設定 50 到 3000 個字元之間的區塊大小、以及介於 1 到 99% 之間的重疊百分比。
+

NOTE: 選擇高重疊百分比可大幅增加儲存需求、只需稍微改善擷取準確度。



** *權限感知*：啟用或停用權限感知回應：
+
*** * 已啟用 * ：存取此知識庫的聊天機器人程式使用者只能從其存取的資料來源取得查詢回應。
*** * 停用 * ：聊天機器人程式的使用者將會使用所有整合式資料來源的內容接收回應。


** * 檔案篩選 * ：設定掃描中包含哪些檔案：
+
*** 在「 * 檔案類型支援 * 」區段中，選擇要包含所有類型的檔案，或選擇要包含在資料來源掃描中的個別檔案類型。
+
如果您包含影像或 PDF 檔案，則 GenAI 的 BlueXP  工作負載工廠會剖析影像中的文字（包括 PDF 文件中的影像），這會產生較高的成本。

+
當包含影像的文字資料時，當掃描的文字資料從您的環境傳送至 AWS 時， GenAI 無法從影像中遮罩個人識別資訊（ PII ）。然而，一旦儲存資料， GenAI 資料庫就會隱藏所有 PII 。

+

NOTE: 您選擇在掃描中包含影像檔案，與知識庫聊天模式有關。如果您在掃描中包含影像檔案，則聊天模式必須支援影像。如果在此選取映像檔案類型，您就無法將知識庫切換至不支援映像檔案的聊天模式。

*** 在 * 檔案修改時間篩選器 * 區段中，選擇根據檔案的修改時間來啟用或停用檔案的包含。如果啟用修改時間篩選，請從清單中選取日期範圍。
+

NOTE: 如果您根據修改日期範圍來包含檔案，只要日期範圍不滿足（檔案尚未在您指定的日期範圍內修改），檔案就會排除在定期掃描之外，而且資料來源也不會包含這些檔案。





. 選擇*新增資料來源*將此資料來源新增至您的知識庫。


--
====