---
sidebar: sidebar 
permalink: connector/requirements-connector.html 
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites, requirements 
summary: 在您建置知識庫之前，請先確定工作負載工廠和 AWS 已正確設定。這包括擁有 AWS 登入認證、部署的 ONTAP 檔案系統 FSX 、其中包含您想要整合至知識庫的資料來源、存取 Amazon bedrock AI 服務等。 
---
= GenAI 連接器需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在為 Amazon Q Business 建立 NetApp 連接器之前，請確保工作負載工廠和 AWS 已正確設定。



== 基本 GenAI 需求

GenAI 的一般需求是您開始使用前所需的環境。

工作負載工廠登入與帳戶:: 您需要 https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["在工作負載工廠設定帳戶"^]使用其中一項登入 https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]。
AWS 認證與權限:: 您需要將 AWS 憑證新增至具有讀取/寫入權限的工作負載工廠，這表示您將在 GenAI 的讀取/寫入模式下使用工作負載工廠。
+
--
目前不支援_基本_模式和_唯讀_模式權限。

設定認證時、如下所示選取權限、可讓您完全存取以管理 ONTAP 檔案系統的 FSX 、並部署及管理知識庫和 chatbot 所需的 GenAI EC2 執行個體和其他 AWS 資源。

https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["瞭解如何將 AWS 認證新增至工作負載工廠"^]

--




== NetApp Connector for Amazon Q Business 的要求

確保您的環境符合 Amazon Q Business 連接器的下列特定要求。

Amazon Q Business 應用程式:: 您必須建立 Amazon Q Business 應用程式，或使用現有的應用程式。
+
--
* 確保應用程式存在於您的 AWS 區域之一。
* 確保您擁有 https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/select-retriever.html["已建立索引"^]應用程式。
* 確保應用程式未處於故障狀態。


--
適用於 ONTAP 檔案系統的 FSX:: 您至少需要一個適用於 ONTAP 檔案系統的 FSX ：
+
--
* NetApp GenAI 引擎將使用一個檔案系統（或建立一個檔案系統（如果不存在））來儲存有關連接器的資訊。
+
此適用於 ONTAP 檔案系統的 FSX 必須使用 FlexVol Volume 。不支援支援的支援。FlexGroup

* 一或多個檔案系統將包含您要新增至連接器的資料來源。
+
一個適用於 ONTAP 檔案系統的 FSX 可同時用於上述兩種用途、或者您可以將多個 FSX 用於 ONTAP 檔案系統。

* 您需要知道 AWS 區域、 VPC 和子網路、這些都是 AWS FSX for ONTAP 檔案系統所在的位置。
* 您需要考慮要套用至屬於此部署一部分的 AWS 資源的標記金鑰 / 值配對（選用）。
* 您必須知道金鑰配對資訊、才能安全地連線至 NetApp AI 引擎執行個體。


https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["瞭解如何部署及管理適用於 ONTAP 檔案系統的 FSX"^]

--

